### ISSUE TITLE
Automatic installation of the plugin fails because the code is unpackaged into the modules folder

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-prestashop#10]
Automatically installing the plugin fails becaue the plugin is un-zipped into the root modules directory rather than a dedicated prestashop folder.

**Comment by hellotaotao** [comment]
Observation:
When installed through prestashop dashboard, the oxipay_prestashop plugin contents are loosely released to prestashop modules folder, rather than grouped under a sub-folder in modules folder. The result is the installation fails silently, and will not show up in prestashop modules page

Solution:
The plugin contents must be first put under a folder named "oxipayprestashop" (identical to the plugin's main .php file name) before being packed into a zip file of any name. In this way, the prestashop installation process will release the plugin contents into correct subfolder under modules folder to make the plugin work.

**Comment by hellotaotao** [comment]
fixed in commit 676139e (release v1.0.10)
